Update SmartyStrategy.php
remove $listener property - since the property is served by the trait.

Fatal error: SmartyModule\View\Strategy\SmartyStrategy and Laminas\EventManager\ListenerAggregateTrait define the same property ($listeners) in the composition of SmartyModule\View\Strategy\SmartyStrategy. However, the definition differs and is considered incompatible. Class was composed in /builds/****/vendor/maglnet/smarty-module/src/SmartyModule/View/Strategy/SmartyStrategy.php on line 17